[package]
name = "backup-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3"
rust-crypto = "0.2"
byteorder = "1.4"
tokio = { version = "1", features = ["full"] }
